"use strict";
let three = 3;
let five = 5;
console.log(`three is equal to 3: ${three == 3}`);
console.log(`\nfive is equal to 5: ${five == 5}`);
console.log(`\nthree is not equal to 5: ${three != 5}`);
console.log(`\nthree is smaller than 5: ${three < 5}`);
console.log(`\nfive is greater than 3: ${five > 3}`);
console.log(`\nthree is equal to 5: ${three == 5}`);
console.log(`\nfive is equal to 3: ${five == 3}`);
console.log(`\nthree is equal to 5: ${three == 5}`);
console.log(`\nthree is greater than 5: ${three > 5}`);
console.log(`\nfive is smaller than 3: ${five < 3}`);
