"use strict";
let apple = "apple";
console.log(`apple is equal to apple: ${apple == "apple"}`);
console.log(`\napple is not equal to apple: ${apple != "apple"}`);
let MyName = "Abdullah Arif";
console.log(`\nAbdllah Arif in lowercase is equal to abdullah arif: ${MyName.toLowerCase() == "abdullah arif"}`);
console.log(`\nAbdllah Arif in lowercase is not equal to abdullah arif: ${MyName.toLowerCase() != "abdullah arif"}`);
let two = 2;
let four = 4;
console.log(`\ntwo is equal to four: ${two == four}`);
console.log(`\ntwo is not equal to four: ${two != four}`);
console.log(`\ntwo is greater than four: ${two > four}`);
console.log(`\ntwo is smaller than four: ${two < four}`);
console.log(`\ntwo is greater than or equal to 5: ${two >= 5}`);
console.log(`\nthree is smaller than or equal to four: ${3 <= four}`);
console.log(`\ntwo is not equal to 4 and two is smaller than 4: ${two != four && two < four} `);
console.log(`\ntwo is  equal to 5 and two is smaller than 1: ${two == 5 && two < 1} `);
console.log(`\nfour is equal to four Or four is greater than 5: ${four == 4 || four > 5}`);
console.log(`\nfour is not equal to four Or four is greater than 5: ${four != 4 || four > 5}`);
let guest = ["Jesse", "Hank", "Jim"];
console.log(`\nHank is in guest list: ${guest.includes("Hank")}`);
console.log(`\nHank is not in guest list: ${!guest.includes("Hank")}`);
